% ##### CORRELATE L2-MNE RESULTS BETWEEN SITES #####

% This script calculates an l2-MNE across a time range and then correlates 
% spatial distribution between the PFC and PAR TEPs using a Speamans 
% correlation.
% Inputs are the grand average structure generated by FieldTrip (EEG), 
% and the lead field generated by Brainstorm.

% Author: Nigel Rogasch, Monash University

clear; close all; clc;

ID = {'001';'002';'004';'005';'006';'007';'008';'009';'010';'011';'012';'013';'014';'015'};
cond = 'average'; % two experimental sessions seperated by at least a week
site = {'pfc';'ppc'}; % two different stimulation sites
tr = {'T0'}; % two different time points within a day - t0 = baseline, t1 = following drug/placebo
useData = 'ica_final';

% Return which computer is running
currentComp = getenv('computername');

% Select path based on computer
if strcmp(currentComp,'CHEWBACCA')
    % Location of 'sound_final' file
    pathDef = 'I:\nmda_tms_eeg\';
else
    % Location of 'sound_final' file
    pathDef = 'D:\nmda_tms_eeg\';
end

% Create input path
if strcmp(useData,'ica_final')
    pathIn = [pathDef,'CLEAN_ICA1\'];
elseif strcmp(useData,'sound_final')
    pathIn = [pathDef,'CLEAN_SOUND2\'];
end

load([pathIn,'MNE\mne_',ID{1},'_',useData,'.mat']);

% Calculate correlations between sites
rho = [];
for idx = 1:size(ID,1)
    for timex = 1:size(mne.toi,2)
        load([pathIn,'MNE\mne_',ID{idx},'_',useData,'.mat']);
        rho(idx,timex) = corr(mne.pfc(:,timex), mne.ppc(:,timex),'type','Spearman');
    end
    fprintf('%s complete\n',ID{idx});
end

% Calculate 95% confidence intervals
meanRho = mean(rho,1);
seRho = std(rho,[],1)./sqrt(length(ID));
CIRho = 1.96*seRho;

% Compare Rho using a rank sum test
rhoTime = 7:300;
time = mne.toi;

rhoP = [];
for rhox = 1:length(rhoTime)
    [~,tp1] = min(abs(-rhoTime(rhox)-time));
    [~,tp2] = min(abs(rhoTime(rhox)-time));
    
    rhoP(rhox) = ranksum(rho(:,tp1),rho(:,tp2));
end

save([pathIn,'MNE\mne_correlations','_',useData,'.mat'],'rho','rhoP');