% ##### CALCULATE DIFFERENCE SCORES FOLLOWING DRUGS #####

% This script calculates the difference in FFT (post-pre) following drug 
% administration. Output are used in cluster-based permutation statistics
% to test a drug x time interaction.
% Inputs are grand averagea structures generated by FieldTrip.

% Author: Nigel Rogasch, Monash University

clear; close all; clc;

con = {'C1';'C2'};
tr = {'t0';'t1'};
state = {'open';'closed'};
u = '_';

pathIn = 'I:\nmda_tms_eeg\REST_FFT_STATS\data\';

for conx = 1:length(con)
    for statex = 1:length(state)
        D1 = load([pathIn,con{conx},'_',state{statex},'_t0']);
        D2 = load([pathIn,con{conx},'_',state{statex},'_t1']);
        power = D1.power;
        power.powspctrm = D2.power.powspctrm - D1.power.powspctrm;
        save([pathIn,con{conx},'_',state{statex},'_diff'],'power');
    end
end

