% ##### PLOT SPATIAL CORRELATIONS BETWEEN SITES #####

% This script plots spatial correlations between TEPs following PFC and PAR
% stimulation in both sensor and source space.
% Inputs are the grand average structure of the EEG data generated by 
% FieldTrip, and the output from mne_correlate_site.m.

% Author: Nigel Rogasch, Monash University

clear; close all; clc;

ID = {'001';'002';'004';'005';'006';'007';'008';'009';'010';'011';'012';'013';'014';'015'};
cond = 'average'; % two experimental sessions seperated by at least a week
site = {'pfc';'ppc'}; % two different stimulation sites
tr = {'T0'}; % two different time points within a day - t0 = baseline, t1 = following drug/placebo
useData = 'sound_final'; % 'sound_final' | 'ica_final'

pathDef = 'I:\nmda_tms_eeg\';

% Create input path
if strcmp(useData,'ica_final')
    pathIn = [pathDef,'CLEAN_ICA\'];
elseif strcmp(useData,'sound_final')
    pathIn = [pathDef,'CLEAN_SOUND\'];
end

% Load data 
addpath ('C:\Users\Nigel\Desktop\fieldtrip-20170815');
ft_defaults;

load([pathIn,'grandAverage_N14.mat']);

% Time variable
time = grandAverage.C1.pfc.T0.time*1000;

%%

N = size(grandAverage.(cond).pfc.T0.individual,1);

% Calculate correlations between sites and perform Fisher's r to z
% transform
for idx = 1:size(grandAverage.(cond).pfc.T0.individual,1)
    for timex = 1:size(grandAverage.(cond).pfc.T0.individual,3)
        rho(idx,timex) = corr(squeeze(grandAverage.(cond).pfc.T0.individual(idx,:,timex))', squeeze(grandAverage.(cond).ppc.T0.individual(idx,:,timex))','type','Spearman');
        z(idx,timex)=.5.*log((1+rho(idx,timex))./(1-rho(idx,timex)));
    end
end

% Calculate mean and 95% confidence intervals for z
avZ = mean(z,1);
seZ = std(z,[],1)./sqrt(N);
CIZ = 1.96*seZ;
CI(1,:) = avZ+CIZ;
CI(2,:) = avZ-CIZ;

% Convert z to r for plotting
for t = 1:size(grandAverage.(cond).pfc.T0.individual,3)
    meanRho(t) = (exp(1)^(2.*avZ(t))-1)/(exp(1)^(2.* avZ(t))+1);
    CIRho(1,t) = (exp(1)^(2.*CI(1,t))-1)/(exp(1)^(2.* CI(1,t))+1);
    CIRho(2,t) = (exp(1)^(2.*CI(2,t))-1)/(exp(1)^(2.* CI(2,t))+1);
end

% Compare Rho using a rank sum test
rhoTime = 15:1000;

for rhox = 1:length(rhoTime)
    [~,tp1] = min(abs(-rhoTime(rhox)-time));
    [~,tp2] = min(abs(rhoTime(rhox)-time));
    
    rhoP(rhox) = ranksum(z(:,tp1),z(:,tp2));
end

fig = figure;
set(gcf,'color','w');

subplot(1,2,1)
plot(time,meanRho,'linewidth',1.5); hold on;
f = fill([time,fliplr(time)],[CIRho(2,:),fliplr(CIRho(1,:))],'b');
set(f,'FaceAlpha',0.3);set(f,'EdgeColor', 'none');
tempLog = zeros(1,length(rhoTime));
tempLog(rhoP >= 0.05) = nan;
plot(rhoTime,tempLog,'r','linewidth',5);
plot([time(1,1),time(1,end)],[0,0],'k--','linewidth',1.5);
plot([0,0],[-4,4],'r--','linewidth',1.5);
set(gca,'xlim',[-300,300],'ylim',[-1,1],'box','off','tickdir','out','linewidth',1.5,'fontsize',12);
xlabel('Time (ms)');
ylabel('Correlation (\rho)');
title('PFC vs PAR (scalp)');
text(-420,1.125,'A','horizontalalignment','center','fontsize',16);

%%

load([pathIn,'MNE\mne_',ID{1},'_',useData,'.mat']);

% Load correlations between sites
load([pathIn,'MNE\mne_correlations_',useData,'.mat']);

rhoTime = 7:300;
time = mne.toi;

% Convert rho values to z scores
for idx = 1:size(rho,1)
    for timex = 1:size(rho,2)
        z(idx,timex)=.5.*log((1+rho(idx,timex))./(1-rho(idx,timex)));
    end
end

% Calculate mean and 95% confidence intervals for z
avZ = mean(z,1);
seZ = std(z,[],1)./sqrt(N);
CIZ = 1.96*seZ;
CI(1,:) = avZ+CIZ;
CI(2,:) = avZ-CIZ;

% Convert z to r for plotting
meanRho = [];
CIRho = [];
for t = 1:size(time,2)
    meanRho(t) = (exp(1)^(2.*avZ(t))-1)/(exp(1)^(2.* avZ(t))+1);
    CIRho(1,t) = (exp(1)^(2.*CI(1,t))-1)/(exp(1)^(2.* CI(1,t))+1);
    CIRho(2,t) = (exp(1)^(2.*CI(2,t))-1)/(exp(1)^(2.* CI(2,t))+1);
end

% Compare Rho using a rank sum test
rhoTime = 15:1000;

for rhox = 1:length(rhoTime)
    [~,tp1] = min(abs(-rhoTime(rhox)-time));
    [~,tp2] = min(abs(rhoTime(rhox)-time));
    
    rhoP(rhox) = ranksum(z(:,tp1),z(:,tp2));
end

subplot(1,2,2)
plot(time,meanRho,'linewidth',1.5); hold on;
f = fill([time,fliplr(time)],[CIRho(2,:),fliplr(CIRho(1,:))],'b');
set(f,'FaceAlpha',0.3);set(f,'EdgeColor', 'none');
tempLog = zeros(1,length(rhoTime));
tempLog(rhoP >= 0.05) = nan;
plot(rhoTime,tempLog,'r','linewidth',5);
plot([time(1,1),time(1,end)],[0,0],'k--','linewidth',1.5);
plot([0,0],[-4,4],'r--','linewidth',1.5);
set(gca,'xlim',[-300,300],'ylim',[-1,1],'box','off','tickdir','out','linewidth',1.5,'fontsize',12);
xlabel('Time (ms)');
ylabel('Correlation (\rho)');
title('PFC vs PAR (source)');
text(-420,1.125,'B','horizontalalignment','center','fontsize',16);

set(fig,'position', [350 550 850 400]);

pathOut = '\figures\';
savename = [pathOut,'TEP_correlations_',useData];
set(gcf,'PaperPositionMode','auto');
print(fig,'-dsvg',savename);
print(fig,'-dpng',savename);