% ##### PLOT INDIVIDUAL WITHIN/BETWEEN TEP EXAMPLES #####

% This script plots TEPs from 5 individual subjects to demonstrate low within
% subject varialibty and high between-subject variability in TEP shape.
% Inputs are the grand average structure of the EEG data generated by 
% FieldTrip.

% Author: Nigel Rogasch, Monash University

clear; close all; clc;

% Which data to use
useData = 'ica_final'; % 'ica_final' | 'sound_final'

% Number of participants
numP = 'N14';

% Stimulation sites
site = {'pfc';'ppc'}; % two different stimulation sites
cond = 'C1'; % 'C1' | 'C2'

pathDef = 'I:\nmda_tms_eeg\';

% Create input path
if strcmp(useData,'ica_final')
    pathIn = [pathDef,'CLEAN_ICA\'];
elseif strcmp(useData,'sound_final')
    pathIn = [pathDef,'CLEAN_SOUND\'];
end

% Load data
load([pathIn,'grandAverage_',numP]);

% Time variable
time = grandAverage.C1.pfc.T0.time*1000;

% subj = 1:14;
subj = 5:9;

fig = figure;
set(gcf,'color','w');
set(fig,'position',[300 400 1000 600]);

plotStruc = [];
plotStruc.time = 1;
plotStruc.dimord = 'chan';
plotStruc.label = grandAverage.C1.pfc.T0.label;

bwidth = 1/length(subj)-0.08;
bheight = 0.25;
bypos = 0.60;
bxpos = linspace(0.1,(1-0.04-bwidth),length(subj));

twidth = 0.09;
theight = 0.09;
horzShift = -0.02;
vertShift = bheight;
horzShift2 = 0.09;

tzlim = [-1,1];

time1 = 70;
time2 = 75;
[~,tp1] = min(abs(time - time1));
[~,tp2] = min(abs(time - time2));

c = get(gca,'colororder');

for subjx = 1:length(subj)
    
    bypos = 0.57;
    pos1 = [bxpos(subjx),bypos,bwidth,bheight];
    subplot('position',pos1)
    plot(time,squeeze(grandAverage.C1.pfc.T0.individual(subj(subjx),17,:)),'b','linewidth',2);hold on;
    plot(time,squeeze(grandAverage.C2.pfc.T0.individual(subj(subjx),17,:)),'r','linewidth',2);
    plot(time1,-6,'k^','linewidth',1.5);
    plot([0,0],[-10,10],'k--','linewidth',1.5);
    set(gca,'xlim',[-100,500],'ylim',[-10,10],'box','off','tickdir','out','linewidth',1.5,'fontsize',12);
    xlabel('Time (ms)');
    ylabel('Amp. (\muV)');
    text(250,20,['S',num2str(subj(subjx))],'horizontalalignment','center','fontsize',14,'fontweight','bold');
    if subjx == 1
        text(-480,0,'PFC','horizontalalignment','center','fontsize',14,'fontweight','bold','rotation',90);
    end
    
    post1 = [bxpos(subjx)+horzShift,bypos+vertShift,twidth,theight];
    subplot('position',post1)
    plotStruc.avg = squeeze(grandAverage.C1.pfc.T0.individual(subj(subjx),:,tp1))';
    cfg = [];
    cfg.layout = 'easycapM11.mat';
    cfg.comment = 'no';
    cfg.interactive = 'no';
    cfg.zlim = tzlim;
    cfg.highlight = 'on';
    cfg.highlightchannel   =  {'Fz'};
    cfg.highlightsymbol    = '.';
    cfg.highlightcolor   = [0.99 0.99 0.99];
    cfg.highlightsize = 20;
    ft_topoplotER(cfg,plotStruc);
    
    post2 = [bxpos(subjx)+horzShift2+horzShift,bypos+vertShift,twidth,theight];
    subplot('position',post2)
    plotStruc.avg = squeeze(grandAverage.C2.pfc.T0.individual(subj(subjx),:,tp1))';
    cfg = [];
    cfg.layout = 'easycapM11.mat';
    cfg.comment = 'no';
    cfg.interactive = 'no';
    cfg.zlim = tzlim;
    cfg.highlight = 'on';
    cfg.highlightchannel   =  {'Fz'};
    cfg.highlightsymbol    = '.';
    cfg.highlightcolor   = [0.99 0.99 0.99];
    cfg.highlightsize = 20;
    ft_topoplotER(cfg,plotStruc);
    
    if subjx == 1
        c = colorbar;
        tmpc = c.Position;
        c.Position = [tmpc(1)-0.17,tmpc(2)-0.02,tmpc(3),0.07];
        c.LineWidth = 1.5;
        c.Ticks = [-1;0;1];
        title(c,'\muV');
    end
    
    bypos = 0.1;
    pos2 = [bxpos(subjx),bypos,bwidth,bheight];
    subplot('position',pos2)
    plot(time,squeeze(grandAverage.C1.ppc.T0.individual(subj(subjx),19,:)),'b','linewidth',2);hold on;
    plot(time,squeeze(grandAverage.C2.pfc.T0.individual(subj(subjx),19,:)),'r','linewidth',2);
    plot(time2,-6,'k^','linewidth',1.5);
    plot([0,0],[-10,10],'k--','linewidth',1.5);
    set(gca,'xlim',[-100,500],'ylim',[-10,10],'box','off','tickdir','out','linewidth',1.5,'fontsize',12);
    xlabel('Time (ms)');
    ylabel('Amp. (\muV)');
    if subjx == 1
        text(-480,0,'PAR','horizontalalignment','center','fontsize',14,'fontweight','bold','rotation',90);
    end
%     if subjx == 5
%         legend({'C1','C2'},'location','southeast','box','off');
%     end
    
    post1 = [bxpos(subjx)+horzShift,bypos+vertShift,twidth,theight];
    subplot('position',post1)
    plotStruc.avg = squeeze(grandAverage.C1.ppc.T0.individual(subj(subjx),:,tp1))';
    cfg = [];
    cfg.layout = 'easycapM11.mat';
    cfg.comment = 'no';
    cfg.interactive = 'no';
    cfg.zlim = tzlim;
    cfg.highlight = 'on';
    cfg.highlightchannel   =  {'Pz'};
    cfg.highlightsymbol    = '.';
    cfg.highlightcolor   = [0.99 0.99 0.99];
    cfg.highlightsize = 20;
    ft_topoplotER(cfg,plotStruc);
    
    post2 = [bxpos(subjx)+horzShift2+horzShift,bypos+vertShift,twidth,theight];
    subplot('position',post2)
    plotStruc.avg = squeeze(grandAverage.C2.ppc.T0.individual(subj(subjx),:,tp1))';
    cfg = [];
    cfg.layout = 'easycapM11.mat';
    cfg.comment = 'no';
    cfg.interactive = 'no';
    cfg.zlim = tzlim;
    cfg.highlight = 'on';
    cfg.highlightchannel   =  {'Pz'};
    cfg.highlightsymbol    = '.';
    cfg.highlightcolor   = [0.99 0.99 0.99];
    cfg.highlightsize = 20;
    ft_topoplotER(cfg,plotStruc);
    
    if subjx == 1
        c = colorbar;
        tmpc = c.Position;
        c.Position = [tmpc(1)-0.17,tmpc(2)-0.02,tmpc(3),0.07];
        c.LineWidth = 1.5;
        c.Ticks = [-1;0;1];
        title(c,'\muV');
    end
end

pathOut = '\figures\';
savename = [pathOut,'TEPs_shape_individual_',useData];
set(gcf,'PaperPositionMode','auto');
print(fig,'-dsvg',savename);
print(fig,'-dpng',savename);